"""
RegulatorIQ — FastAPI backend

Run with:
    uvicorn backend.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""
import requests as http_requests
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from loguru import logger

from backend.models.responses import HealthResponse
from backend.routes.ask import router as ask_router
from backend.routes.documents import router as documents_router
from backend.routes.ingest import router as ingest_router
from pipeline.indexing.qdrant_store import QdrantStore

app = FastAPI(
    title="RegulatorIQ API",
    description="RAG-powered Q&A over Indian financial regulations (SEBI + RBI)",
    version="1.0.0",
)

# Allow the Next.js frontend (running on port 3000) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register all route groups under /api prefix
app.include_router(ask_router, prefix="/api")
app.include_router(documents_router, prefix="/api")
app.include_router(ingest_router, prefix="/api")


@app.get("/health", response_model=HealthResponse, tags=["Health"])
async def health():
    """
    Health check — confirms Qdrant and Ollama are reachable.
    Call this first to make sure the system is fully operational.
    """
    # Check Qdrant
    qdrant_ok = False
    docs_indexed = 0
    try:
        store = QdrantStore()
        docs_indexed = store.count()
        qdrant_ok = True
    except Exception:
        pass

    # Check Ollama
    ollama_ok = False
    try:
        r = http_requests.get("http://localhost:11434/api/tags", timeout=3)
        ollama_ok = r.status_code == 200
    except Exception:
        pass

    status = "ok" if (qdrant_ok and ollama_ok) else "degraded"
    logger.info(f"Health check: status={status} qdrant={qdrant_ok} ollama={ollama_ok}")

    return HealthResponse(
        status=status,
        qdrant=qdrant_ok,
        ollama=ollama_ok,
        documents_indexed=docs_indexed,
    )


@app.get("/", tags=["Root"])
async def root():
    return {
        "name": "RegulatorIQ API",
        "docs": "/docs",
        "health": "/health",
        "endpoints": ["/api/ask", "/api/documents", "/api/ingest"],
    }
